Aufgabe 5.1

In [22]:
import numpy as np
import matplotlib.pyplot as plt

xn = np.arange(3)
yn = -np.arange(4)
x, y =np.meshgrid(xn, yn) #

print(x)
print(y)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[ 0  0  0]
 [-1 -1 -1]
 [-2 -2 -2]
 [-3 -3 -3]]


In [11]:
xn

array([0, 1, 2])

In [12]:
yn

array([ 0, -1, -2, -3])

In [17]:
print(x * np.ones(4).reshape((-1, 1)).astype(int)) #norm (4,1) #alt np.array([1,1,1,1]) 3 bei float ist punkt bei int nicht boom

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [23]:
print(np.ones(3).astype(int) * yn.reshape((-1, 1)))

[[ 0  0  0]
 [-1 -1 -1]
 [-2 -2 -2]
 [-3 -3 -3]]


In [29]:
print((x * np.ones(4).reshape((-1, 1))).dtype)

float64


In [25]:
print((x * np.ones(4).reshape((-1, 1)).astype(int)).dtype)

int32
